### ISSUE TITLE
Enhance pm_data_complete to deal with exception

### ISSUE THREAD

**Issue by ateucher** [bcgov/rcaaqs#13]
Functionality for PM<sub>2.5</sub> CAAQS calculation has been implemented, including evaluating data completeness criteria. However, `pm_data_complete` currently does not deal with the exception to the data completeness criteria as outlined in the [Guidance Document](http://www.ccme.ca/files/Resources/air/aqms/pn_1483_gdad_eng.pdf) (first paragraph, page 11). It should be enhanced to do so.

**Comment by stephhazlitt** [comment]
The [`rcaaqs` README](https://github.com/bcgov/rcaaqs) demonstrates the `pm_data_complete` function and highlights the step where, at this time, the exception is captured. This issue should incorporate this step into the `pm_data_complete` function.

``` r
## Then join the results to the data completeness data frame and select 
## only the results that are valid. This process could be more efficent
ann_98_per <- left_join(ann_98_per, pm_completeness, 
                        by = c("ems_id", "year"))
ann_98_per <- filter(ann_98_per, use_annual | (exceed & annual_valid))
glimpse(ann_98_per)
#> Observations: 23
#> Variables: 15
#> $ ems_id               <chr> "0220205", "0310162", "0310162", "0310162...
#> $ year                 <int> 2012, 2011, 2012, 2013, 2011, 2012, 2013,...
```
