### ISSUE TITLE
rcaaqs R package enhancements

### ISSUE THREAD

**Issue by stephhazlitt** [bcgov/rcaaqs#14]
## Background
[Environmental Reporting BC](http://www2.gov.bc.ca/gov/content/environment/research-monitoring-reporting/reporting/environmental-reporting-bc) provides access to scientific data and information about our environment and how it relates to British Columbians. This information comes in the form of [indicators](http://www2.gov.bc.ca/gov/content/environment/research-monitoring-reporting/reporting/environmental-reporting-bc/about-environmental-reporting) that examine the state and trends of different aspects of our environment.

[Environmental Reporting BC](http://www2.gov.bc.ca/gov/content/environment/research-monitoring-reporting/reporting/environmental-reporting-bc) follows the [Canadian Council of Ministers of the Environment (CCME)](http://www.ccme.ca/index.html) Air Quality Management System for reporting on [air quality in B.C.](http://www2.gov.bc.ca/gov/content?id=C7BA872425D9498084C808B98EA7AF52)

### Story
As an analyst with Environmental Reporting BC, I need some enhancements completed to the [R](https://www.r-project.org/) package [rcaaqs](https://github.com/bcgov/rcaaqs) to facilitate calculating the Canadian Ambient Air Quality Standard (CAAQS) metric values for implementing the CCME [Air Quality Management System](http://www.ccme.ca/en/resources/air/aqms.html).

## How to contribute
We are offering this issue as a paid opportunity through the [BCDevExchange](https://bcdevexchange.org/) experimental procurement model, [Code-with-Us](https://github.com/BCDevExchange/code-with-us/wiki/1.-Intro-&-Disclaimer).

To work on this issue, we are accepting proposals until **3:00 PM Pacific Standard Time (PST) on Friday, November 18th, 2016**. After that time, we will evaluate the proposals we have received, and assign the work to one person by end of the day Monday, November 21st.  [How assignment works](https://github.com/BCDevExchange/code-with-us/wiki/4.-How-assignment-works)

### What to include in your proposal
We will evaluate and score proposals by the following **criteria**:

1. The date by which you can complete the issue (10 points).
2. A short (around 200 words or less would be nice) summary of your proposed approach (40 points).
3. References to your relevant experience and demonstrated ability to do the work (50 points). For example, a link to your GitHub projects.
4. To qualify for assignment your proposal must meet a minimum score of 80 points out of 100 (Mandatory).
5. With your proposal, you must attach a copy of the [Code-with-Us Terms](https://github.com/bcgov/rcaaqs/blob/master/Code-with-Us_Terms_EnvReportBC.pdf), with the required information asked for in the "Acceptance" section of the Terms inserted into the document (Mandatory).

The highest scoring proposal will get the assignment.

### How to submit your proposal
Please submit your proposal to [Stephanie.Hazlitt@gov.bc.ca](mailto:Stephanie.Hazlitt@gov.bc.ca) by **3:00 PM Pacific Standard Time (PST) on Friday, November 18th, 2016**.  Please put "**rcaaqs enhancements for Environmental Reporting BC**" in the subject line. 

## Acceptance Criteria
To be paid for this opportunity we need you to:

1) Ensure [rcaaqs](https://github.com/bcgov/rcaaqs) includes functions for calculating the:
     i. CAAQS metric for Ozone (close [Issue #2](https://github.com/bcgov/rcaaqs/issues/2))
    ii. Metrics for SO<sub>2</sub> (close [Issue #11](https://github.com/bcgov/rcaaqs/issues/11))
    iii. Metrics for NO<sub>2</sub> (close [Issue #12](https://github.com/bcgov/rcaaqs/issues/12)) 
    
    *Note that functionality for the CAAQS metric for PM<sub>2.5</sub> is already implemented and should be a good starting point for the above. See the [README](https://github.com/bcgov/rcaaqs/blob/master/README.md) for a simple example.

2) For each of the above, ensure that the steps include functions for:
    i. Calculating data completeness according to documentation, accounting for exceptions where indicated.
    ii. Calculating daily values according to documentation.
    iii. Calculating annual values from daily values according to documentation.
    iv. Calculating a three-year metric from annual values according to documentation.  

3) Ensure that the functionality for evaluating the data completeness criteria for PM<sub>2.5</sub> is enhanced to deal with exceptions (close [Issue #13](https://github.com/bcgov/rcaaqs/issues/13)).

4) Ensure [rcaaqs](https://github.com/bcgov/rcaaqs) includes functions for excluding data influenced by Transboundary Flows & Exceptional Events and calculating the revised metric value (close [Issue #5](https://github.com/bcgov/rcaaqs/issues/5)).

5) Ensure functions are small, testable, and reusable, following the DRY (do not repeat yourself) principle. As there is significant overlap in methodology for fine particulate matter (PM<sub>2.5</sub>), ground-level ozone (O<sub>3</sub>), sulphur dioxide (SO<sub>2</sub>), and nitrogen dioxide (NO<sub>2</sub>), core functions should be reused in the calculation steps for these parameters wherever possible.

6) Ensure all exported functions have clear and comprehensive documentation. Using the 'Roxygen' package to generate documentation is encouraged.

7) Ensure all functions have good unit tests written (preferably using the 'testthat' package) to ensure correct calculations.

8) Ensure that upon completion, the [rcaaqs](https://github.com/bcgov/rcaaqs) package passes all continuous integration builds using Travis CI (already implemented).

9) Ensure that all code is original code written by the assignee, with the exception of functions from other R packages included as dependencies. If it is necessary to include third-party code, ensure that the code is released under an open-source license that is compatible with the Apache 2.0 license, and its source and original license is explicitly documented.

If you are assigned the opportunity, be sure to submit your completed enhancements a few days before the completion date to give us time to review. It is likely we may ask you for a round of changes and you will want to have the time to complete any changes before the agreed deadline.

[How payment works](https://github.com/BCDevExchange/code-with-us/wiki/5.-How-payment-works)

## Questions, Comments, Suggestions? 
Please post your questions in the comments section below.

**Comment by stephhazlitt** [comment]
Hi folks -- myself and @ateucher are the Opportunity Contacts for this Issue. Please post any questions you have here and we'll do our best to respond promptly.

**Comment by lselzer** [comment]
Can foreign developers participate?

**Comment by stephhazlitt** [comment]
@lselzer Any developer can respond to an opportunity, there are no restrictions based on geographical location. All respondents will be subject to the same evaluation and success criteria.

**Comment by ateucher** [comment]
I have updated the repository `README` file with a simple example of the current functionality as implemented for PM<sub>2.5</sub>. Thanks @daattali for the suggestion.

**Comment by stephhazlitt** [comment]
Hello Subscribers: Just a friendly reminder to submit your proposal before 12:00 PM PST today. Thanks for your interest!

**Comment by stephhazlitt** [comment]
Thanks to everyone who provided feedback on our first [Code-with-Us experiment](https://github.com/BCDevExchange/code-with-us/wiki/1.-Intro-&-Disclaimer). We have heard excitement from the [R](https://www.r-project.org/) community about Code-with-Us, and also that the initial timeline for closing the issue was ambitious. 

Based on this feedback, we have decided to **re-open the paid opportunity, asking that you provide the date by which you can complete the issue**. The updated opportunity will be open until **3:00 PM Pacific Standard Time (PST) on Friday, November 18th, 2016**. The [issue](https://github.com/bcgov/rcaaqs/issues/14) has been edited to reflect the updated proposal criteria and submission timeline. 

Please feel free to provide any further feedback on this issue or Code-with-Us below, or you can email me at the address on my profile.

**Comment by stephhazlitt** [comment]
Just a friendly reminder that proposals for this Code-with-Us opportunity are due this Friday, November 18th by 3PM PST (Pacific Standard Time). Please e-mail proposals to [Stephanie.Hazlitt@gov.bc.ca](mailto:stephanie.hazlitt@gov.bc.ca) and feel free to ask questions or provide feedback.

**Comment by stephhazlitt** [comment]
Hi folks. There was a request for clarification on [Issue #13](https://github.com/bcgov/rcaaqs/issues/13) -- closing [Issue #13](https://github.com/bcgov/rcaaqs/issues/13) is part of the acceptance criteria for this Code-With-Us opportunity. I have edited [Issue #13](https://github.com/bcgov/rcaaqs/issues/13) to try and make the requested enhancement more clear for everyone. Please feel free to ask further questions on any of the acceptance criteria.

**Comment by stephhazlitt** [comment]
Hello Subscribers: Just a friendly reminder to submit your proposal before 3PM PST (Pacific Standard Time) today. Thanks for your interest!

**Comment by stephhazlitt** [comment]
Thanks everyone who submitted a proposal. The proposal period is now closed. @ateucher and I will be reviewing them and will let you know by end of day Monday who is assigned.

**Comment by stephhazlitt** [comment]
Thank you to everyone who submitted a proposal for our `rcaaqs R package enhancements` Code-with-Us opportunity. Based on the proposal evaluation criteria, @nograpes scored the highest, so we’re assigning him to work on this issue until December 5th. 

To others who submitted a proposal, please feel free to [contact me](mailto:stephanize.hazlitt@gov.bc.ca) if you would like feedback on your proposal or you have comments or feedback on the Code-with-Us experiment.

**Comment by daattali** [comment]
Congrats @nograpes!

**Comment by ateucher** [comment]
Hi @nograpes. I just merged #16, so you'll probably want to update your fork. Also, just a quick suggestion - I often find a nice way to work on a feature/enahncement is to open a pull request early and mark it as "Not ready for merge". Then as you push to your branch the changes show up in the pull request and it is easy to comment on the changes.

**Comment by nograpes** [comment]
Thanks for the heads up, I'll do that later on tonight.

**Comment by ateucher** [comment]
The pull request by @nograpes (#17) satisfies the acceptance criteria for this Code With Us opportunity as of commit https://github.com/bcgov/rcaaqs/pull/17/commits/6fabf602e963ab536f13f967a4f8105474f19222. There are two very small changes pending (adding a test and fixing one small bug) before we merge.

**Comment by ateucher** [comment]
Thanks for the great work @nograpes. Your Pull Request (#17) has been merged!
