### ISSUE TITLE
Calling OlsonNames() repeatedly is EXTREMELY slow - calculate it once and store it

### ISSUE THREAD

**Issue by daattali** [bcgov/rcaaqs#15]
When I was testing out the package, I noticed that `percent_valid_days()` is noticeably slow and was annoying to call multiple times.  It turns out that making a call to `OlsonNames()` is a very expensive operation. I suggest making this function call just once and then storing it so that any subsequent call to `percent_valid_days()` will use the already-calculated value. On the sample `pm25_sample_data` dataset, I observed a 10x speed improvement when doing that.

**Comment by ateucher** [comment]
Thanks very much for finding that @daattali - I didn't realize that `OlsonNames()` was so slow.

**Comment by daattali** [comment]
I didn't either, I just got frustrated with calling it so used profvis.
Such a useful package
