### ISSUE TITLE
wrap as.POSIXct around strptime call in format_date()?

### ISSUE THREAD

**Issue by stephhazlitt** [bcgov/rcaaqs#18]
I am getting an error with a date-time column even after running it through rcaaqs::format_date() [error..unsupported class POSIXlt, POSIXt]. I wonder if wrapping strptime() in the format_date() function with as.POSIXct would [fix this](http://stackoverflow.com/questions/30063190/problems-with-dplyr-and-posixlt-data)?

**Comment by ateucher** [comment]
There is an `lt` (`TRUE/FALSE`) argument to `lubridate::fast_strptime` (used in `format_date`) that tells whether or not the returned date object should be `POSIXlt` (default `TRUE`). Setting to `FALSE` in `format_date` should fix it.

**Comment by stephhazlitt** [comment]
Closed by 3e9b819a77517d84087c68241842384c944e6961
