### ISSUE TITLE
Add functionality for calculating the CAAQS ozone metric value

### ISSUE THREAD

**Issue by ateucher** [bcgov/rcaaqs#2]
Will probably need to generalize a lot of PM<sub>2.5</sub> functions

**Comment by stephhazlitt** [comment]
Functionality for assessing data completeness criteria and calculating the CAAQS ozone metric should follow the methodologies, procedures, and requirements in the [Guidance Document for the Achievement  Determination (GDAD) for the Canadian Ambient Air Quality Standards for Fine Particulate Matter and Ozone](http://www.ccme.ca/files/Resources/air/aqms/pn_1483_gdad_eng.pdf), pages 13-16. 
- The CAAQS ozone metric is the 3-year average of the annual 4th-highest daily maximum 8-hour average concentrations.
- The general approach is written as a script in [ozone-caaqs-analysis, lines 1 to 84](https://github.com/bcgov/ozone-caaqs-analysis/blob/master/03_analysis.R). 
- Raw, verified air quality data is available in the [BC Data Catalogue under the Open Government License-BC](https://catalogue.data.gov.bc.ca/dataset/air-quality-monitoring-verified-hourly-data-and-station-data). 
- The results of the 2011-2013 CAAQS ozone metric calculations are also [open](https://catalogue.data.gov.bc.ca/dataset/bc-ambient-air-quality-standards-reporting-results-ozone) and should be used to compare and test function outputs.

**Comment by ateucher** [comment]
**NOTE:** Due to a change in `dplyr 0.5.0` where `arrange()` now ignores groupings defined using `group_by()`, the method for selecting the fourth highest daily maximum [here (lines 48-54)](https://github.com/bcgov/ozone-caaqs-analysis/blob/master/03_analysis.R#L48-L54) will no longer work. A different solution will be required.
