### ISSUE TITLE
refactor dplyr code for tidyeval framework

### ISSUE THREAD

**Issue by ateucher** [bcgov/rcaaqs#24]
dplyr 0.7 has hit the streets with big changes to dealing with non-standard evaluation - a new system called tidyeval. See `vignette("programming")`.

This isn't urgent yet, as the underscored versions of the dplyr verbs are deprecated, but not defunct (yet).

**Comment by stephhazlitt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Maintenance](https://trello.com/c/LfWS0fKl/9-maintenance)

**Comment by ateucher** [comment]
I took a first try at this when I added the new `plot_station_instruments` function.

**Comment by ateucher** [comment]
Some good resources here: http://maraaverick.rbind.io/2017/08/tidyeval-resource-roundup/
