### ISSUE TITLE
Don't export all functions

### ISSUE THREAD

**Issue by steffilazerte** [bcgov/rcaaqs#33]

**Comment by stephhazlitt** [comment]
@ateucher  I think a review of which functions are exported-not exported would be useful. A few internal functions are also handy for a user starting with messier data than the examples (e.g. `clean_neg` which I re-exported with [054ec3c](https://github.com/bcgov/rcaaqs/commit/054ec3c651e2b560570b4dd1f9c43c662935b7dc)). Also, wondering if `date_fill` might be replaced with `tidyr::complete`?

**Comment by ateucher** [comment]
Other functions to consider re-exporting:
- [x] `plot_summary()`
- [ ] `cut_management()`

**Comment by stephhazlitt** [comment]
Done or decided not to do.
