### ISSUE TITLE
Be consistent with argument for data

### ISSUE THREAD

**Issue by steffilazerte** [bcgov/rcaaqs#37]
Various functions use different argument names for the incoming dataset. For example:
- `dat`
- `df`
- `data`

Suggest we pick one to be consistent (`df` is probably the best)

**Comment by boshek** [comment]
`data` is more standard no? I think about `lm()`, `plot()` or `ggplot2()`

**Comment by steffilazerte** [comment]
True, I was thinking along the lines that `data()` is an R base function (well `utils`), and I've heard the argument that it's best to avoid it. But perhaps that refers to `data` in scripts as opposed to in functions.

Other than that I quite like `data` as an argument

**Comment by ateucher** [comment]
I think `data` works as an argument name. Thanks both!
