### ISSUE TITLE
New CAAQS Thresholds

### ISSUE THREAD

**Issue by jeromerobles** [bcgov/rcaaqs#55]
2020 CAAQS for PM2.5 and Ozone changes the limits specified in the achievement_levels.rda and management_levels.rda. The following are the changes:
     PM2.5_24h: 28 to 27
     PM2.5_annual: 10 to 8.8
     Ozone: 63 to 62
Can you modify?

**Comment by ateucher** [comment]
This can be done here: https://github.com/bcgov/rcaaqs/blob/master/data-raw/caaqs_levels.R. And then re-run that file to regenerate the internal `achievement_levels` and `management_levels` datasets
