### ISSUE TITLE
Erron on assign_airzone() with bcmaps::airzones()

### ISSUE THREAD

**Issue by steffilazerte** [bcgov/rcaaqs#58]
Test failures occur in `test-8_airzone_metric.R` because the `bcmaps()::airzones()` spatial data is a bit wonky. However, using `sf::st_make_valid()` fixes the problem.

Ideally this would be fixed in bcmaps, is that an option?

Otherwise, the tests and examples should probably use `sf::st_make_valid()`

Reprex of the issue:

``` r
library(rcaaqs)
library(bcmaps)
#> Loading required package: sf
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1; sf_use_s2() is TRUE
    
d <- data.frame(lat = 48.407326, lon = -123.329773, site = "Victoria")
az <- airzones()
#> airzones was updated on NULL
d_az <- assign_airzone(d, az, station_id = "site")
#> Error in s2_geography_from_wkb(x, oriented = oriented, check = check): Evaluation error: Found 1 feature with invalid spherical geometry.
#> [5] Loop 0 is not valid: Edge 441 has duplicate vertex with edge 446.
    
az <- sf::st_make_valid(airzones())
d_az <- assign_airzone(d, az, station_id = "site")
# No problem now!
```

<sup>Created on 2022-02-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by stephhazlitt** [comment]
It does seem to be a {bcmaps} issue, as this works with {bcdata}:

``` r
library(rcaaqs)
library(bcdata)
#> 
#> Attaching package: 'bcdata'
#> The following object is masked from 'package:stats':
#> 
#>     filter

airz <- bcdc_get_data("e8eeefc4-2826-47bc-8430-85703d328516",
                      resource = "4cea4b22-36a3-4ea7-9346-7e872e747076")
#> Reading the data using the read_sf function from the sf package.

d <- data.frame(lat = 48.407326, lon = -123.329773, site = "Victoria")

d_airz <- assign_airzone(d, airz, station_id = "site")
d_airz
#>        lat       lon     site        airzone
#> 1 48.40733 -123.3298 Victoria Georgia Strait
```

<sup>Created on 2022-02-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by boshek** [comment]
@steffilazerte  I think if you update bcmaps with the GitHub dev version, this will work. @ateucher fixed this but we have not yet released to CRAN.

**Comment by steffilazerte** [comment]
Unfortunately I get the same error with bcmaps v1.0.2.9000 from GitHub (main branch)

**Comment by steffilazerte** [comment]
BUT! If I use airzones(force = TRUE), it actually downloads the data (as opposed to...?) and THEN it works.

**Comment by stephhazlitt** [comment]
That is as expected I think, as your cached version of `airzones.rds` was borked, so `force = TRUE` grabbed it again with the fixed code on the master branch. Another way, and my default first step when I hit an issue with {bcmaps} is to clear the cache. e.g., `bcmaps::delete_cache('airzones.rds')`
