### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by mddefp** [bcgov/rcaaqs#6]
Here is what I get when I try to download:

Downloading GitHub repo bcgov/rcaaqs@master
from URL https://api.github.com/repos/bcgov/rcaaqs/zipball/master
Error in curl::curl_fetch_memory(url, handle = handle) : 
  SSL connect error

**Comment by ateucher** [comment]
Can you paste the output of `sessionInfo()` here please?

Are you by any chance on Linux? It seems a few people have had this issue lately: http://stackoverflow.com/questions/35055715/ssl-connect-error-in-httr-curl

**Comment by mddefp** [comment]
> sessionInfo()
> R version 3.2.3 (2015-12-10)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=French_Canada.1252  LC_CTYPE=French_Canada.1252    LC_MONETARY=French_Canada.1252 LC_NUMERIC=C  
[5] LC_TIME=French_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] httr_1.1.0      RCurl_1.95-4.7  bitops_1.0-6    devtools_1.10.0

loaded via a namespace (and not attached):
[1] R6_2.1.2      tools_3.2.3   curl_0.9.5    memoise_1.0.0 git2r_0.13.1  digest_0.6.9

**Comment by ateucher** [comment]
Thanks @mddefp. All of your packages are up to date, and as you're on Windows it's not likely to be related to the Linux issue I posted. I think it's likely something to do with `curl`, and not the `rcaaqs` package itself, but to be sure, can you please try to install another R package from github? One that might be of interest is [Ropenaq](https://github.com/masalmon/ropenaq).

``` r
library(devtools)
install_github("masalmon/Ropenaq")
```

**Comment by mddefp** [comment]
Indeed, the problem is on my computer at work. With install_github ("masalmon / Ropenaq") I have the same error.
_Downloading GitHub repo masalmon / Ropenaq @ Masters
from URL https://api.github.com/repos/masalmon/Ropenaq/zipball/master
Error in curl :: curl_fetch_memory (url, handle = handle):
   SSL connect error_

I installed rcaaqs on my personal computer at home without problems.

Do you have an idea of what can issue SSL error?
or
Is there an other way to get rcaaqs package?

Thanks

**Comment by stephhazlitt** [comment]
Hi @mddefp. I think this might be due to an outdated version of curl, see this [StackOverflow Issue](http://www.verkltas.club/questions/35055715/ssl-connect-error-in-httr-curl/35064714). I suggest installing curl explicitly first then try installing rcaaqs.

**Comment by stephhazlitt** [comment]
Hi again @mddefp -- did you sort out your install error with [rcaaqs](https://github.com/bcgov/rcaaqs)?

**Comment by mddefp** [comment]
Hi, I got it by taking the  .zip path in the console error. Not the best way, but that worked.

**Comment by ateucher** [comment]
Glad you figured out a way to get it @mddefp! The package is definitely a work in progress, so if you have any feedback on it we would really appreciate it.
