### ISSUE TITLE
quantile2 throws an error when probs=1 and type="caaqs"

### ISSUE THREAD

**Issue by DonnaHaga** [bcgov/rcaaqs#62]
R version 4.3.1, `rcaaqs` version 0.3.1.900

When using the `quantile2` function to calculate percentiles and error is thrown when `probs=1` and `type="caaqs`:

```
library(rcaaqs)

pm25_sample_data %>%
  dplyr::group_by(year) %>%
  dplyr::summarise(p100=rcaaqs:::quantile2(value,
                                           probs=1,
                                           na.rm=FALSE,
                                           type="caaqs"))
```
This is the error:
![rcaaqs_quantile2_probs1_caaqs](https://github.com/bcgov/rcaaqs/assets/24443567/ecbec811-eeae-4167-866e-90da918fd492)

When a different `probs` value is chosen there isn't an issue:
```
pm25_sample_data %>%
  dplyr::group_by(year) %>%
  dplyr::summarise(p99=rcaaqs:::quantile2(value,
                                           probs=0.99,
                                           na.rm=FALSE,
                                           type="caaqs"))
```
Here's the output:

![rcaaqs_quantile2_probs099_caaqs](https://github.com/bcgov/rcaaqs/assets/24443567/70086af6-50f3-45ef-bf23-cd7b82d5b872)

**Comment by stephhazlitt** [comment]
Interesting.

It works when you use one of the `stats::quantile` `type` argument options:

``` r
rcaaqs::pm25_sample_data |> 
  dplyr::group_by(year) |> 
  dplyr::summarise(p100=rcaaqs:::quantile2(value,
                                           probs = 1,
                                           na.rm = FALSE,
                                           type = 7))
#> # A tibble: 4 × 2
#>    year  p100
#>   <int> <dbl>
#> 1  2011   103
#> 2  2012   116
#> 3  2013   122
#> 4  2014    20
```

Which is the same as using `stats::quantile()` directly (the `rcaaqs:::quantile2` internal function is a wrapper around `stats::quantile`):

``` r
rcaaqs::pm25_sample_data |> 
  dplyr::group_by(year) |> 
  dplyr::summarise(p100=stats::quantile(value,
                                        probs = 1,
                                        na.rm = FALSE,
                                        type = 7))
#> # A tibble: 4 × 2
#>    year  p100
#>   <int> <dbl>
#> 1  2011   103
#> 2  2012   116
#> 3  2013   122
#> 4  2014    20
```

The `warning` is telling us the issue is with`dplyr::summarise()`, and that some deprecated code in `dplyr` has changed some behaviour for the `"caaqs"` method:

``` r
rcaaqs::pm25_sample_data |> 
  dplyr::group_by(year) |> 
  dplyr::summarise(p99=rcaaqs:::quantile2(value,
                                          probs = 1,
                                          na.rm = FALSE,
                                          type = "caaqs"))
#> Warning: Returning more (or less) than 1 row per `summarise()` group was deprecated in
#> dplyr 1.1.0.
#> ℹ Please use `reframe()` instead.
#> ℹ When switching from `summarise()` to `reframe()`, remember that `reframe()`
#>   always returns an ungrouped data frame and adjust accordingly.
#> Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
#> generated.
#> `summarise()` has grouped output by 'year'. You can override using the
#> `.groups` argument.
#> # A tibble: 0 × 2
#> # Groups:   year [0]
#> # ℹ 2 variables: year <int>, p99 <dbl>

> lifecycle::last_lifecycle_warnings()
[[1]]
<warning/lifecycle_warning_deprecated>
Warning:
Returning more (or less) than 1 row per `summarise()` group was deprecated in dplyr
1.1.0.
ℹ Please use `reframe()` instead.
ℹ When switching from `summarise()` to `reframe()`, remember that `reframe()` always
  returns an ungrouped data frame and adjust accordingly.
---
Backtrace:
    ▆
 1. ├─dplyr::summarise(...)
 2. └─dplyr:::summarise.grouped_df(...)
 3.   └─dplyr:::summarise_deprecate_variable_size()
```


Looking at the `type = "caaqs"` [code](https://github.com/bcgov/rcaaqs/blob/master/R/yearly_stat.R#L309-L359), I can see that when prob = 1 nothing is returned for each year, and `dplyr::summarise` is complaining.

``` r
x <- rcaaqs::pm25_sample_data |> dplyr::filter(year == 2014) |> dplyr::pull(value)

probs <- .99

x <- sort(x, decreasing = TRUE)
n <- length(x)
i.d <- probs * n
i <- floor(i.d)
ret <- x[n - i]
ret
#> [1] 20

probs <- 1

x <- sort(x, decreasing = TRUE)
n <- length(x)
i.d <- probs * n
i <- floor(i.d)
ret <- x[n - i]
ret
#> numeric(0)
```

I'd love to know if this code ever worked with `prob = 1`, or how `dplyr` pre-v1.1.0 behaved? But moving forward, given all the other quantile methods return the first integer in the vector of values when `prob = 1`, I am guessing the `"caaqs"` method should do the same? If so, maybe tweaking the code to return x[1] when `i` == `n`?

``` r
x <- rcaaqs::pm25_sample_data |> dplyr::filter(year == 2014) |> dplyr::arrange(desc(value)) |> dplyr::pull(value)

probs <- 1

x <- sort(x, decreasing = TRUE)
n <- length(x)
i.d <- probs * n
i <- floor(i.d)

if (n == i) {
  ret <- x[1]
} else
ret <- x[n - i]
ret
#> [1] 20
```

**Comment by DonnaHaga** [comment]
Thanks @stephhazlitt! Yes that is my understanding - that `x[1]` should be returned when `type="caaqs"` and `probs=1` i.e. the maximum value in `x` should be returned. I think your proposed update will do the trick for this case.

**Comment by stephhazlitt** [comment]
> Thanks @stephhazlitt! Yes that is my understanding - that `x[1]` should be returned when `type="caaqs"` and `probs=1` i.e. the maximum value in `x` should be returned. I think your proposed update will do the trick for this case.

OK, thanks for confirming @DonnaHaga. I'll try and put up a pull request today which this behaviour change.

**Comment by KarHarker** [comment]
Issue closed with https://github.com/bcgov/rcaaqs/pull/64, thanks @stephhazlitt
