### ISSUE TITLE
Rename default branch from master to main

### ISSUE THREAD

**Issue by stephhazlitt** [bcgov/rcaaqs#63]
https://github.com/github/renaming

**Comment by ateucher** [comment]
Check out `usethis::git_default_branch_rename()`! It fixes things both locally and on GitHub.

**Comment by stephhazlitt** [comment]
@ateucher done!  What is the most elegant way to update a local clone that might still have `master`? I think GitHub provides this in a pop-up but I missed it 💨

**Comment by ateucher** [comment]
I think [this](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes).

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
